
server:
  port: 9001

#注册到eureka
eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.13.128:8081/eurekaserver/eureka/

#命名service
spring:
  application:
    name: order-service
  main:
    #解决：多个接口上的@FeignClient(“相同服务名”)会报错，overriding is disabled，即出现了相同的Bean名
    allow-bean-definition-overriding: true
#开启Swagger
swagger:
  enable: true


#添加feign
feign:
  hystrix:
    enabled: true
  client:
    config:
      default:
        connectTimeout: 2000
        readTimeout: 2000