
server:
  port: 9001

#\u6307\u5B9A\u6CE8\u518C\u4E2D\u5FC3\u5730\u5740
eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.13.128:8081/eurekaserver/eureka/

#\u670D\u52A1\u7684\u540D\u79F0
spring:
  application:
    name: order-service